version: '3.9'

services:
  platform_dev:
    container_name: admin
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.production
    ports:
      - '${PORT}:${PORT}'
