version: '3.9'

services:
  panel_dev:
    container_name: panel_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - '${PORT}:${PORT}'
