import { Question } from '../../model/types/question';

export const mockGetQuestionsList: Question[] = [
	{
		id: '1',
		title: 'Task 1',
		description: 'Task description 1',
		rate: 4,
		complexity: 4,
		imgSrc: 'task1.jpg',
		keywords: ['task', 'tag1'],
		resources: ['resource1'],
		author: 'Author A',
		type: 'task',
	},
	{
		id: '2',
		title: 'Task 2',
		description: 'Question description 1',
		rate: 3,
		complexity: 3,
		imgSrc: 'question1.jpg',
		keywords: ['question', 'tag2'],
		resources: ['resource2'],
		author: 'Author B',
		type: 'question',
		criteria: 'Criteria for question 1',
	},
	{
		id: '3',
		title: 'Task 3',
		description: 'Test description 1',
		rate: 5,
		complexity: 5,
		imgSrc: 'test1.jpg',
		keywords: ['test', 'tag3'],
		resources: ['resource3'],
		author: 'Author C',
		type: 'test',
		options: [
			{ id: 1, answer: 'Option 1' },
			{ id: 2, answer: 'Option 2' },
			{ id: 3, answer: 'Option 3' },
		],
		correctOptionId: 1,
		explanation: 'Explanation for test 1',
		time: '30 minutes',
	},

	{
		id: '4',
		title: 'Task 4',
		description: 'Task description 2',
		rate: 4,
		complexity: 4,
		imgSrc: 'task2.jpg',
		keywords: ['task', 'tag4'],
		resources: ['resource4'],
		author: 'Author D',
		type: 'task',
	},
	{
		id: '5',
		title: 'Task 5',
		description: 'Question description 2',
		rate: 3,
		complexity: 3,
		imgSrc: 'question2.jpg',
		keywords: ['question', 'tag5'],
		resources: ['resource5'],
		author: 'Author E',
		type: 'question',
		criteria: 'Criteria for question 2',
	},
	{
		id: '6',
		title: 'Task 6',
		description: 'Test description 2',
		rate: 5,
		complexity: 5,
		imgSrc: 'test2.jpg',
		keywords: ['test', 'tag6'],
		resources: ['resource6'],
		author: 'Author F',
		type: 'test',
		options: [
			{ id: 1, answer: 'Option 1' },
			{ id: 2, answer: 'Option 2' },
			{ id: 3, answer: 'Option 3' },
		],
		correctOptionId: 1,
		explanation: 'Explanation for test 2',
		time: '30 minutes',
	},

	{
		id: '7',
		title: 'Task 7',
		description: 'Task description 3',
		rate: 4,
		complexity: 4,
		imgSrc: 'task3.jpg',
		keywords: ['task', 'tag7'],
		resources: ['resource7'],
		author: 'Author G',
		type: 'task',
	},
	{
		id: '8',
		title: 'Task 8',
		description: 'Question description 3',
		rate: 3,
		complexity: 3,
		imgSrc: 'question3.jpg',
		keywords: ['question', 'tag8'],
		resources: ['resource8'],
		author: 'Author H',
		type: 'question',
		criteria: 'Criteria for question 3',
	},
	{
		id: '9',
		title: 'Task 9',
		description: 'Test description 3',
		rate: 5,
		complexity: 5,
		imgSrc: 'test3.jpg',
		keywords: ['test', 'tag9'],
		resources: ['resource9'],
		author: 'Author I',
		type: 'test',
		options: [
			{ id: 1, answer: 'Option 1' },
			{ id: 2, answer: 'Option 2' },
			{ id: 3, answer: 'Option 3' },
		],
		correctOptionId: 1,
		explanation: 'Explanation for test 3',
		time: '30 minutes',
	},
	{
		id: '10',
		title: 'Task 10',
		description: 'Test description 3',
		rate: 5,
		complexity: 5,
		imgSrc: 'test3.jpg',
		keywords: ['test', 'tag9'],
		resources: ['resource9'],
		author: 'Author I',
		type: 'test',
		options: [
			{ id: 1, answer: 'Option 1' },
			{ id: 2, answer: 'Option 2' },
			{ id: 3, answer: 'Option 3' },
		],
		correctOptionId: 1,
		explanation: 'Explanation for test 3',
		time: '30 minutes',
	},
	{
		id: '11',
		title: 'Task 11',
		description: 'Test description 3',
		rate: 5,
		complexity: 5,
		imgSrc: 'test3.jpg',
		keywords: ['test', 'tag9'],
		resources: ['resource9'],
		author: 'Author I',
		type: 'test',
		options: [
			{ id: 1, answer: 'Option 1' },
			{ id: 2, answer: 'Option 2' },
			{ id: 3, answer: 'Option 3' },
		],
		correctOptionId: 1,
		explanation: 'Explanation for test 3',
		time: '30 minutes',
	},
	{
		id: '12',
		title: 'Task 12',
		description: 'Test description 3',
		rate: 5,
		complexity: 5,
		imgSrc: 'test3.jpg',
		keywords: ['test', 'tag9'],
		resources: ['resource9'],
		author: 'Author I',
		type: 'test',
		options: [
			{ id: 1, answer: 'Option 1' },
			{ id: 2, answer: 'Option 2' },
			{ id: 3, answer: 'Option 3' },
		],
		correctOptionId: 1,
		explanation: 'Explanation for test 3',
		time: '30 minutes',
	},
	{
		id: '13',
		title: 'Task 13',
		description: 'Test description 3',
		rate: 5,
		complexity: 5,
		imgSrc: 'test3.jpg',
		keywords: ['test', 'tag9'],
		resources: ['resource9'],
		author: 'Author I',
		type: 'test',
		options: [
			{ id: 1, answer: 'Option 1' },
			{ id: 2, answer: 'Option 2' },
			{ id: 3, answer: 'Option 3' },
		],
		correctOptionId: 1,
		explanation: 'Explanation for test 3',
		time: '30 minutes',
	},
	{
		id: '14',
		title: 'Task 14',
		description: 'Test description 3',
		rate: 5,
		complexity: 5,
		imgSrc: 'test3.jpg',
		keywords: ['test', 'tag9'],
		resources: ['resource9'],
		author: 'Author I',
		type: 'test',
		options: [
			{ id: 1, answer: 'Option 1' },
			{ id: 2, answer: 'Option 2' },
			{ id: 3, answer: 'Option 3' },
		],
		correctOptionId: 1,
		explanation: 'Explanation for test 3',
		time: '30 minutes',
	},
];
