name: Deploy Panel/Admin

on:
  push:
    branches:
      - develop
      - main

env:
  SERVICE_NAME_TEST: panel
  SERVICE_NAME_PRODUCTION: admin

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS for test
        if: github.ref == 'refs/heads/develop' # Действие для ветки develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_TEST }}
          username: ${{ secrets.VPS_USERNAME_TEST }}
          key: ${{ secrets.VPS_SSH_KEY_TEST }}
          script: |
            docker-compose --env-file .env.test up -d --build ${{ env.SERVICE_NAME_TEST }}
            docker image prune -f

      - name: Deploy to VPS for production
        if: github.ref == 'refs/heads/main' # Действие для ветки main (production)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_PRODUCTION }}
          username: ${{ secrets.VPS_USERNAME_PRODUCTION }}
          key: ${{ secrets.VPS_SSH_KEY_PRODUCTION }}
          script: |
            docker-compose --env-file .env.production up -d --build ${{ env.SERVICE_NAME_PRODUCTION }}
            docker image prune -f
